### ISSUE TITLE
Warning: Unknown argument(s): {'unit_divisor': 1024}

### ISSUE THREAD

**Issue by ghost** [blachlylab/pyega#1]
Hi,
I'm getting the following when trying to download a file (same for a whole dataset) from the EGA:

[2018-10-16 20:49:47 +0200] File Id: 'EGAF00000865484'(5768819038 bytes).
[2018-10-16 20:49:47 +0200] Download starting [using 1 connection(s)]...
[2018-10-16 20:49:47 +0200] Unknown argument(s): {'unit_divisor': 1024}
[2018-10-16 20:49:52 +0200] retry attempt 1
[2018-10-16 20:49:52 +0200] Download starting [using 1 connection(s)]...
[2018-10-16 20:49:52 +0200] Unknown argument(s): {'unit_divisor': 1024}
[2018-10-16 20:49:57 +0200] retry attempt 2
[2018-10-16 20:49:57 +0200] Download starting [using 1 connection(s)]...
[2018-10-16 20:49:57 +0200] Unknown argument(s): {'unit_divisor': 1024}
[2018-10-16 20:50:02 +0200] retry attempt 3
[2018-10-16 20:50:02 +0200] Download starting [using 1 connection(s)]...
[2018-10-16 20:50:02 +0200] Unknown argument(s): {'unit_divisor': 1024}
Traceback (most recent call last):
  File "pyega3/pyega3.py", line 439, in <module>
    main()
  File "pyega3/pyega3.py", line 433, in main
    download_file_retry( token, args.identifier, file_name, file_size, check_sum, args.connections, key, args.saveto, genomic_range_args )
  File "pyega3/pyega3.py", line 333, in download_file_retry
    raise e
  File "pyega3/pyega3.py", line 328, in download_file_retry
    download_file(token, file_id, file_size, check_sum, num_connections, key, output_file)
  File "pyega3/pyega3.py", line 274, in download_file
    with tqdm(total=int(file_size), unit='B', unit_scale=True, unit_divisor=1024) as pbar:
  File "/opt/install/dir/anaconda/envs/ICGC/lib/python3.6/site-packages/tqdm-4.7.2-py3.6.egg/tqdm/_tqdm.py", line 427, in __init__
Warning: Unknown argument(s): {'unit_divisor': 1024}

**Comment by jblachly** [comment]
@petrsha Thanks for the report. I notice you opened the same issue in EGA-archive/ega-download-client: https://github.com/EGA-archive/ega-download-client/issues/22

It looks like an issue with the tqdm package.

Please note that you are using pyega3 which EGA appears to have built based on my pyega program. I have no involvement with pyega3.
