### ISSUE TITLE
urllib3 error suddenly ?

### ISSUE THREAD

**Issue by j4jes** [blachlylab/pyega#2]
I had pyega working on some downloads then it suddenly stopped working due to urllib3 and requests py packages. I'm not sure what changed in my environement, I guess it's possible that I did a conda pkg install that updated urllib3 to an incompatible version ??  Very frustrating because I've been downloading this uk_biobank file for three weeks, and I'm almost done. The pyega option takes a bit longer than the previous sftp solution which offered file compression. At least this way I have built in md5 checksumming.

moldach@cortex:~/uk_biobank $ module load anaconda3
moldach@cortex:~/uk_biobank $ pyega3 -d -c 4 -cf CREDENTIALS_FILE fetch EGAF00001835265
EGA python client version 3.0.27
[debugging]
[2019-02-08 14:28:58 -0500] Starting new HTTPS connection (1): ega.ebi.ac.uk:8443
[2019-02-08 14:28:59 -0500] https://ega.ebi.ac.uk:8443 "POST /ega-openid-connect-server/token HTTP/1.1" 200 None
[2019-02-08 14:28:59 -0500] <Response [200]>

[2019-02-08 14:28:59 -0500] Request URL : https://ega.ebi.ac.uk:8443/ega-openid-connect-server/token
[2019-02-08 14:28:59 -0500] Response    :
 
[2019-02-08 14:28:59 -0500] Authentication success for user 'shantala.haridass@mail.mcgill.ca'
[2019-02-08 14:28:59 -0500] Starting new HTTPS connection (1): ega.ebi.ac.uk:8051
Traceback (most recent call last):
  File "/home/meaney.lab/moldach/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/meaney.lab/moldach/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/home/meaney.lab/moldach/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "/share/apps/anaconda3/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/share/apps/anaconda3/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/share/apps/anaconda3/lib/python3.6/http/client.py", line 258, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/share/apps/anaconda3/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
  File "/home/meaney.lab/moldach/.local/lib/python3.6/site-packages/urllib3/contrib/pyopenssl.py", line 299, in recv_into
    raise SocketError(str(e))
OSError: (104, 'ECONNRESET')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/meaney.lab/moldach/.local/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/home/meaney.lab/moldach/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/meaney.lab/moldach/.local/lib/python3.6/site-packages/urllib3/util/retry.py", line 367, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/meaney.lab/moldach/.local/lib/python3.6/site-packages/urllib3/packages/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/home/meaney.lab/moldach/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/meaney.lab/moldach/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/home/meaney.lab/moldach/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "/share/apps/anaconda3/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/share/apps/anaconda3/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/share/apps/anaconda3/lib/python3.6/http/client.py", line 258, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/share/apps/anaconda3/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
  File "/home/meaney.lab/moldach/.local/lib/python3.6/site-packages/urllib3/contrib/pyopenssl.py", line 299, in recv_into
    raise SocketError(str(e))
urllib3.exceptions.ProtocolError: ('Connection aborted.', OSError("(104, 'ECONNRESET')",))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/share/apps/anaconda3/bin/pyega3", line 11, in <module>
    sys.exit(main())
  File "/home/meaney.lab/moldach/.local/lib/python3.6/site-packages/pyega3/pyega3.py", line 432, in main
    file_name, file_size, check_sum = get_file_name_size_md5( token, args.identifier )            
  File "/home/meaney.lab/moldach/.local/lib/python3.6/site-packages/pyega3/pyega3.py", line 146, in get_file_name_size_md5
    r = requests.get(url, headers = headers)
  File "/home/meaney.lab/moldach/.local/lib/python3.6/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/home/meaney.lab/moldach/.local/lib/python3.6/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/meaney.lab/moldach/.local/lib/python3.6/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/meaney.lab/moldach/.local/lib/python3.6/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/home/meaney.lab/moldach/.local/lib/python3.6/site-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', OSError("(104, 'ECONNRESET')",))
moldach@cortex:~/uk_biobank $

**Comment by j4jes** [comment]
I just tried updating pyega through Bioconda  (pyega3-3.0.21-py36_0 0 --> pyega3-3.0.21-py36_1)
then I tried the pip3 install:   pip3.6 install pyega3 --user   which installed pyega3-3.0.30.

I then realized it's a problem with the EGA server !   So this is not a pyega issue.
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

https://www.ebi.ac.uk/ega/home

**Comment by jblachly** [comment]
@j4jes Thanks for the report. Hopefully, it is just a server issue and will be resolved soon.

EMBL/EBI actually liked my pyega so much that they have forked the codebase to build pyega3. I will try to mark this repository as archived and redirect to the updated version @ EMBL's github account.
