### ISSUE TITLE
persistent option?

### ISSUE THREAD

**Issue by j4jes** [blachlylab/pyega#4]
Would it be possible to add a -p persistent option to automatically resume dropped connection or broken transfers ? The EGA archive gateway has been getting more usage and when I start pyega3 downloads they rarely make it through the entire weekend or even through the night, so I keep them inside screen sessions and monitor them remotely. 

Ive been downloading with -c 4 and found that sometimes it does not resume downloading, and will give md5 does not match, then start back at 0%. This was the case for me here after it had reached 99% then got stuck while trying to concatenate the slice files:

[2019-03-25 09:21:14 -0400] MD5 does NOT match - corrupted download
[2019-03-25 09:21:19 -0400] retry attempt 1
[2019-03-25 09:21:19 -0400] Download starting [using 4 connection(s)]...
  0%|                                                                                                                                                    | 0.00/156G [00:00<?, ?B/s][2019-03-25 09:21:19 -0400] Request URL : https://ega.ebi.ac.uk:8051/elixir/data/files/EGAF00001835279?destinationFormat=plain

Three days of downloading gone! Thanks for your help.

**Comment by j4jes** [comment]
This last week has been hell trying to download from EGA. I've downloaded this file four times now, and it always disappears when I reach 100%, then I must start over. I'm going to try again without -c chunking and see how that goes, but my download time will be increased ten fold.

[jesse@corpus uk_biobank]$ pyega3 -d -c 20 -cf CREDENTIALS_FILE fetch EGAF00001835283
...
[2019-03-29 02:44:49 -0400] Response headers: {'X-Application-Context': 'zuulserver:8051', 'WWW-Authenticate': 'Bearer realm="oauth2-resource", error="invalid_token", error_description="Invalid token: eyJraWQiOiJyc2ExIiwiYWxnIjoiUlMyNTYifQ.eyJzdWIiOiJzaGFudGFsYS5oYXJpZGFzc0BtYWlsLm1jZ2lsbC5jYSIsImF6cCI6ImYyMGNkMmQzLTY4MmEtNDU2OC1hNTNlLTQyNjJlZjU0YzhmNCIsImlzcyI6Imh0dHBzOlwvXC9lZ2EuZWJpLmFjLnVrOjg0NDNcL2VnYS1vcGVuaWQtY29ubmVjdC1zZXJ2ZXJcLyIsImV4cCI6MTU1MzgzMDY2NCwiaWF0IjoxNTUzODI3MDY0LCJqdGkiOiI3OTZjNWYyNC0wZTA0LTQ2YmItODdjYi1kNTczNDAwM2VjNDQifQ.lN9vIrO-PuAaMVJ88xKenEmw6HpwyxiTJ2ygw58UIGnRcqTXd-gVlvTyAvH1EYweaBPesSrQE8yGxe6oo68SQaE2y0G-GmbDth99sxBIrGiY3uwzKVw7JXfN3pbm-DEsKL_zM14yBMPdZ4QWP7-nXemU9dzSpuMAdcIN2k0p7MU"', 'Date': 'Fri, 29 Mar 2019 06:44:48 GMT', 'Content-Type': 'application/json;charset=UTF-8', 'Transfer-Encoding': 'chunked'}
[2019-03-29 02:44:49 -0400] https://ega.ebi.ac.uk:8051 "GET /elixir/data/files/EGAF00001835283?destinationFormat=plain HTTP/1.1" 401 None
[2019-03-29 02:44:49 -0400] Request URL : https://ega.ebi.ac.uk:8051/elixir/data/files/EGAF00001835283?destinationFormat=plain
[2019-03-29 02:44:49 -0400] Response headers: {'X-Application-Context': 'zuulserver:8051', 'WWW-Authenticate': 'Bearer realm="oauth2-resource", error="invalid_token", error_description="Invalid token: eyJraWQiOiJyc2ExIiwiYWxnIjoiUlMyNTYifQ.eyJzdWIiOiJzaGFudGFsYS5oYXJpZGFzc0BtYWlsLm1jZ2lsbC5jYSIsImF6cCI6ImYyMGNkMmQzLTY4MmEtNDU2OC1hNTNlLTQyNjJlZjU0YzhmNCIsImlzcyI6Imh0dHBzOlwvXC9lZ2EuZWJpLmFjLnVrOjg0NDNcL2VnYS1vcGVuaWQtY29ubmVjdC1zZXJ2ZXJcLyIsImV4cCI6MTU1MzgzMDY2NCwiaWF0IjoxNTUzODI3MDY0LCJqdGkiOiI3OTZjNWYyNC0wZTA0LTQ2YmItODdjYi1kNTczNDAwM2VjNDQifQ.lN9vIrO-PuAaMVJ88xKenEmw6HpwyxiTJ2ygw58UIGnRcqTXd-gVlvTyAvH1EYweaBPesSrQE8yGxe6oo68SQaE2y0G-GmbDth99sxBIrGiY3uwzKVw7JXfN3pbm-DEsKL_zM14yBMPdZ4QWP7-nXemU9dzSpuMAdcIN2k0p7MU"', 'Date': 'Fri, 29 Mar 2019 06:44:48 GMT', 'Content-Type': 'application/json;charset=UTF-8', 'Transfer-Encoding': 'chunked'}
[2019-03-29 02:44:49 -0400] https://ega.ebi.ac.uk:8051 "GET /elixir/data/files/EGAF00001835283?destinationFormat=plain HTTP/1.1" 401 None
[2019-03-29 02:44:49 -0400] Request URL : https://ega.ebi.ac.uk:8051/elixir/data/files/EGAF00001835283?destinationFormat=plain
[2019-03-29 02:44:49 -0400] Response headers: {'X-Application-Context': 'zuulserver:8051', 'WWW-Authenticate': 'Bearer realm="oauth2-resource", error="invalid_token", error_description="Invalid token: eyJraWQiOiJyc2ExIiwiYWxnIjoiUlMyNTYifQ.eyJzdWIiOiJzaGFudGFsYS5oYXJpZGFzc0BtYWlsLm1jZ2lsbC5jYSIsImF6cCI6ImYyMGNkMmQzLTY4MmEtNDU2OC1hNTNlLTQyNjJlZjU0YzhmNCIsImlzcyI6Imh0dHBzOlwvXC9lZ2EuZWJpLmFjLnVrOjg0NDNcL2VnYS1vcGVuaWQtY29ubmVjdC1zZXJ2ZXJcLyIsImV4cCI6MTU1MzgzMDY2NCwiaWF0IjoxNTUzODI3MDY0LCJqdGkiOiI3OTZjNWYyNC0wZTA0LTQ2YmItODdjYi1kNTczNDAwM2VjNDQifQ.lN9vIrO-PuAaMVJ88xKenEmw6HpwyxiTJ2ygw58UIGnRcqTXd-gVlvTyAvH1EYweaBPesSrQE8yGxe6oo68SQaE2y0G-GmbDth99sxBIrGiY3uwzKVw7JXfN3pbm-DEsKL_zM14yBMPdZ4QWP7-nXemU9dzSpuMAdcIN2k0p7MU"', 'Date': 'Fri, 29 Mar 2019 06:44:48 GMT', 'Content-Type': 'application/json;charset=UTF-8', 'Transfer-Encoding': 'chunked'}

[2019-03-29 02:44:49 -0400] 401 Client Error:  for url: https://ega.ebi.ac.uk:8051/elixir/data/files/EGAF00001835283?destinationFormat=plain
Traceback (most recent call last):
  File "/home/jesse/.local/bin/pyega3", line 11, in <module>
    load_entry_point('pyega3==3.0.27', 'console_scripts', 'pyega3')()
  File "/home/jesse/.local/lib/python3.6/site-packages/pyega3/pyega3.py", line 433, in main
    download_file_retry( token, args.identifier, file_name, file_size, check_sum, args.connections, key, args.saveto, genomic_range_args )
  File "/home/jesse/.local/lib/python3.6/site-packages/pyega3/pyega3.py", line 333, in download_file_retry
    raise e
  File "/home/jesse/.local/lib/python3.6/site-packages/pyega3/pyega3.py", line 328, in download_file_retry
    download_file(token, file_id, file_size, check_sum, num_connections, key, output_file)
  File "/home/jesse/.local/lib/python3.6/site-packages/pyega3/pyega3.py", line 279, in download_file
    for part_file_name in executor.map(download_file_slice_ ,params):
  File "/usr/lib64/python3.6/concurrent/futures/_base.py", line 586, in result_iterator
    yield fs.pop().result()
  File "/usr/lib64/python3.6/concurrent/futures/_base.py", line 432, in result
    return self.__get_result()
  File "/usr/lib64/python3.6/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/usr/lib64/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/jesse/.local/lib/python3.6/site-packages/pyega3/pyega3.py", line 193, in download_file_slice_
    return download_file_slice(*args)
  File "/home/jesse/.local/lib/python3.6/site-packages/pyega3/pyega3.py", line 183, in download_file_slice
    r.raise_for_status()
  File "/home/jesse/.local/lib/python3.6/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error:  for url: https://ega.ebi.ac.uk:8051/elixir/data/files/EGAF00001835283?destinationFormat=plain

After this, the slice files are gone !

[jesse@corpus uk_biobank]$ cd EGAF00001835283/
[jesse@corpus EGAF00001835283]$ ls
[jesse@corpus EGAF00001835283]$ ls -al
total 0
drwxrwxr-x 1 jesse jesse   0 Mar 29 02:43 .
drwxrwxr-x 1 jesse jesse 158 Mar 28 00:07 ..
[jesse@corpus EGAF00001835283]$

**Comment by jblachly** [comment]
Sorry you are having these problems @j4jes 

The EMBL/EBI actually liked this project so much that they took over and maintain it at https://github.com/EGA-archive/ega-download-client

I apologize for the confusion, and hope that they can help you. I will try to archive this repo.

WIth kind regards
